### ISSUE TITLE
Test example error

### ISSUE THREAD

**Issue by Mokatani** [CIRCL/PyMISP#77]
Hi All,
i have installed PyMISP and configured it as it stays in readme. 
When i run the example command to test my PyMISP, i  receive an error:

```
python last.py -l 10
- /usr/local/lib/python2.7/dist-packages/pymisp-2.4.54-py2.7.egg/pymisp/api.py:18: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
- /usr/local/lib/python2.7/dist-packages/pymisp-2.4.54-py2.7.egg/pymisp/mispevent.py:41: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
- /usr/local/lib/python2.7/dist-packages/pymisp-2.4.54-py2.7.egg/pymisp/api.py:36: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
- Traceback (most recent call last):
 -  File "last.py", line 44, in <module>
 -  misp = init(misp_url, misp_key)
 -  File "last.py", line 15, in init
 -  return PyMISP(url, key, misp_verifycert, 'json')
  File "/usr/local/lib/python2.7/dist-packages/pymisp-2.4.54-py2.7.egg/pymisp/api.py", line 105, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://mymispURL/). Please make sure the API key and the URL are correct (http/https is required): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

I am sure that i have enter the right information in key.py file (URL and API key)
How can i fix this issue?

Thanks and best regards,
Mohammad

**Comment by Rafiot** [comment]
Hi,

Do you have a self signed certificate? If yes, you also need to pass `misp_verifycert = False` in `keys.py`
https://github.com/CIRCL/PyMISP/blob/master/examples/keys.py.sample#L6

Raphaël

**Comment by Rafiot** [comment]
I assume it was the problem, please reopen if needed.
